apiVersion: v1
kind: Service
metadata:
  name: ml-infra-demo-service
  namespace: prod
spec:
  selector:
    app: ml-infra-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
